window.DECK =
[
  {
    "key": "major_00",
    "name": "The Fool (0)",
    "imgUpright": "images/major_00_u.jpg",
    "imgReversed": "images/major_00_r.jpg",
    "upright": "Traditional: new beginnings, innocence, trust in the path. Inner reading: the heart wants space to explore without guarantees. Let wonder outrun caution for one step. Gentle prompt: What tiny experiment would feel playful and safe today?",
    "reversed": "Traditional: recklessness, hesitation, poor planning. Inner reading: fear dresses up as perfectionism. You can begin imperfectly. Gentle prompt: What small safeguard would let you take the first honest step?",
    "uprightLong": "The Fool asks you to act before certainty appears. Every new chapter starts with partial information, and waiting for perfect readiness often hides fear of imperfection. This energy supports experimentation: signing up for that class, reaching out to a mentor, testing an idea instead of analyzing it endlessly. The Fool reminds you that feedback is the teacher readiness could never be. Embrace curiosity as your navigation tool — it will lead you to experiences logic can’t plan. Trust yourself to adapt along the way; agility matters more than guarantees. Make a move small enough to feel safe but real enough to gather evidence. You don’t need confidence to begin; you need a first step.",
    "reversedLong": "When The Fool appears reversed, the leap forward feels tangled in fear, procrastination, or the illusion that you must be ‘ready’ before moving. It reveals a moment when spontaneity meets hesitation — when your curiosity has to push through overthinking. This energy often arises when you’re protecting yourself from imagined failure rather than actual danger. It might also signal recklessness: acting without grounding or direction. Both are sides of the same coin — one holds back, the other rushes in. The antidote is intention. Pause long enough to name your purpose, choose one modest action, and create a simple safeguard. Momentum begins by proving to yourself you can take the smallest true step.",
    "promptUpright": "What one small action could you take today that says, *“I’m willing to find out”*?",
    "promptReversed": "What simple precaution would make taking the first real step feel safe enough?"
  },
  {
    "key": "major_01",
    "name": "The Magician (1)",
    "imgUpright": "images/major_01_u.jpg",
    "imgReversed": "images/major_01_r.jpg",
    "upright": "Traditional: will, skill, manifestation. Inner reading: focus turns scattered sparks into a flame. Choose one intention and channel everything there. Gentle prompt: What single action today would make the rest easier or irrelevant?",
    "reversed": "Traditional: manipulation, untapped potential, misalignment. Inner reading: your energy leaks in too many directions. Re-center before acting. Gentle prompt: What will you lovingly set down so your yes can be wholehearted?",
    "uprightLong": "The Magician turns ideas into matter through focus. It teaches that competence grows from commitment, not confidence. You already have tools — skills, contacts, time — but they scatter without aim. Choose one project, define success in your language, and act consistently. Energy follows direction. Cut noise: one capture system, one workspace, one daily ritual. Translate intention into a calendar block and a checklist you’ll actually use. Creation here is iterative: build, test, refine. Speak your plan aloud to make it real and recruit support. You’re not waiting for permission; you’re practicing power by practicing.",
    "reversedLong": "Reversed, The Magician reveals leaks in attention or honesty. You may be multitasking yourself into mediocrity or selling an image that drains integrity. Re-ground in clarity: what outcome truly matters and why? Simplify tools, detach from performing productivity, and rebuild credibility with yourself through follow‑through. Replace five open projects with one finished deliverable. If manipulation is present — yours or others’ — step back, tell the truth, and let results speak. Power returns when alignment does.",
    "promptUpright": "Which current idea deserves your full attention for the next seven days?",
    "promptReversed": "What promise to yourself needs to be kept before starting something new?"
  },
  {
    "key": "major_02",
    "name": "The High Priestess (2)",
    "imgUpright": "images/major_02_u.jpg",
    "imgReversed": "images/major_02_r.jpg",
    "upright": "Traditional: intuition, mystery, inner knowing. Inner reading: the quiet answer is already present. Make room to hear it. Gentle prompt: Where can you choose silence over seeking more input?",
    "reversed": "Traditional: secrets, blocked intuition, surface noise. Inner reading: you’re scrolling past the whisper. Reduce noise, then listen again. Gentle prompt: What boundary could protect your inner yes/no today?",
    "uprightLong": "The High Priestess values pause over noise. In practice, this means trusting your evaluation before asking for ten more opinions. Insight ripens in silence — journaling, walking, or simply sitting with ambiguity. She reminds you that instinct is data collected by experience; give it credit. Choose a question, reduce inputs, and listen for the small, steady signal beneath anxiety. Acting from quiet confidence prevents external chaos from steering your choices. You don’t need to explain your knowing to everyone; you need to honor it with one clear step.",
    "reversedLong": "When reversed, distractions overpower intuition. You may be consuming content instead of creating understanding. The High Priestess reversed asks for digital and emotional decluttering — fewer inputs, clearer voice. Step back from the feed, postpone nonessential advice, and create a container for your own perspective to form. Slow information intake until your inner clarity catches up; then move with conviction.",
    "promptUpright": "Where could you replace seeking advice with listening inward for one day?",
    "promptReversed": "What boundary (screen, conversation, or thought loop) could protect your inner signal today?"
  },
  {
    "key": "major_03",
    "name": "The Empress (3)",
    "imgUpright": "images/major_03_u.jpg",
    "imgReversed": "images/major_03_r.jpg",
    "upright": "Traditional: abundance, nurture, creation. Inner reading: softness grows results. Tend what’s alive rather than forcing growth. Gentle prompt: What would supporting your body make possible for your mind today?",
    "reversed": "Traditional: creative block, overgiving, neglect. Inner reading: generosity needs roots. Refill first, then share. Gentle prompt: Where do you need to mother yourself before mothering the world?",
    "uprightLong": "The Empress teaches sustainable productivity: growth through care, not pressure. Creativity flourishes when your nervous system feels safe. Eat, rest, hydrate, bring beauty into your space — these are strategic acts, not indulgence. The more nourished you feel, the more naturally you produce meaningful work and relationships. Replace punishment with pacing. Treat your body as a collaborator, not a vehicle you drive to empty. Nurture environments and routines that let ideas germinate without force.",
    "reversedLong": "Reversed, The Empress highlights over‑giving or depletion. You might nurture others while starving your own soil. Pause any caretaking that breeds resentment. Replenish resources before offering more. Audit your yeses: which are generous, which are fearful? Creativity returns when you are resourced. Productivity built on exhaustion collapses; kindness restores momentum.",
    "promptUpright": "What simple physical comfort could help your creativity breathe today?",
    "promptReversed": "Where can you replace giving with receiving without guilt?"
  },
  {
    "key": "major_04",
    "name": "The Emperor (4)",
    "imgUpright": "images/major_04_u.jpg",
    "imgReversed": "images/major_04_r.jpg",
    "upright": "Traditional: structure, authority, boundaries. Inner reading: stability is a kindness. Name the rule that frees you. Gentle prompt: What simple system would remove friction for the next week?",
    "reversed": "Traditional: rigidity, control, rebellion. Inner reading: control protects anxiety, not truth. Switch from force to framework. Gentle prompt: What rule can be softened without losing safety?",
    "uprightLong": "The Emperor embodies systems that protect freedom. Discipline, scheduling, and clear roles create room for creativity to roam safely. Set boundaries that define where work ends and rest begins. Leadership here means consistency, not dominance. Build habits that carry you on low‑motivation days: a planning ritual, a time block for deep work, a daily shutdown routine. Good structure feels like relief.",
    "reversedLong": "When reversed, control morphs into rigidity. You may cling to plans to avoid uncertainty or resist authority out of pride. Flexibility is strength in motion. Review your rules: keep those that bring stability, release those that suffocate flow. Update your system to match the season you’re in, not the one you miss.",
    "promptUpright": "What small structure would make tomorrow smoother automatically?",
    "promptReversed": "Which personal rule could you relax this week to regain ease?"
  },
  {
    "key": "major_05",
    "name": "The Hierophant (5)",
    "imgUpright": "images/major_05_u.jpg",
    "imgReversed": "images/major_05_r.jpg",
    "upright": "Traditional: tradition, teaching, shared values. Inner reading: learn the form before you rewrite it. Gentle prompt: What trustworthy source or ritual could ground you today?",
    "reversed": "Traditional: nonconformity, dogma questioned. Inner reading: it’s time to keep the meaning and release the rule. Gentle prompt: Which inherited belief no longer serves your living truth?",
    "uprightLong": "The Hierophant represents learning frameworks — mentors, courses, traditions — that transmit tested wisdom. Practical spirituality means using structure to deepen meaning, not to obey blindly. Study fundamentals, then adapt them to your context. Seek teachers who empower autonomy. Ritualize what works: a weekly review, a morning practice, an accountability partner. Let form serve freedom.",
    "reversedLong": "Reversed, the card challenges conformity. Outdated systems may stifle growth; questioning them is progress, not rebellion. Keep the principle, redesign the ritual. Choose mentors who welcome your voice. Authenticity matters more than approval. Write a new rule that honors the same value with more life in it.",
    "promptUpright": "Which proven method or mentor could strengthen your current learning curve?",
    "promptReversed": "What inherited belief or routine could you update to match who you’ve become?”
  },
  {
    "key": "major_06",
    "name": "The Lovers (6)",
    "imgUpright": "images/major_06_u.jpg",
    "imgReversed": "images/major_06_r.jpg",
    "upright": "Traditional: union, choice, values alignment. Inner reading: choose the path that chooses you back. Gentle prompt: Which option deepens self-respect even if it’s harder?",
    "reversed": "Traditional: misalignment, indecision, disharmony. Inner reading: when values blur, choices stall. Re-choose your why. Gentle prompt: What value of yours wants to be honored first?",
    "uprightLong": "The Lovers isn’t only about romance — it’s about values in alignment. Every relationship, goal, or decision mirrors how honestly you’re living your priorities. When upright, it suggests your heart and mind are ready to cooperate: you can choose what feels right and makes sense. This card encourages integrity — making commitments that support your well‑being, not drain it. Evaluate your yeses and ensure they reflect your deeper truth, not obligation. Harmony grows when actions match beliefs. Choose the option that lets you respect yourself in the morning.",
    "reversedLong": "Reversed, The Lovers highlights inner contradiction — saying yes out of fear of loss or guilt rather than genuine desire. It can also indicate people‑pleasing or neglecting your own voice. Press pause on big decisions and realign with your values. Real love (self, romantic, or professional) thrives on transparency, not compliance. Return to what matters, then choose.",
    "promptUpright": "What choice would make you feel most at peace with yourself tomorrow morning?",
    "promptReversed": "Where might you be mistaking agreement for harmony?”
  },
  {
    "key": "major_07",
    "name": "The Chariot (7)",
    "imgUpright": "images/major_07_u.jpg",
    "imgReversed": "images/major_07_r.jpg",
    "upright": "Traditional: determination, direction, victory. Inner reading: well-held opposites move you forward. Gentle prompt: What two impulses can you harness toward the same aim?",
    "reversed": "Traditional: lack of control, drift, force without focus. Inner reading: speed without aim is stress. Gentle prompt: What destination would make saying no easier today?",
    "uprightLong": "The Chariot represents self‑direction through focus and discipline. Progress happens when emotion and logic pull together, not apart. Define a target clearly — even a small one — and move toward it steadily, adjusting rather than doubting. Obstacles become training grounds for mastery. Determination here is emotional intelligence in motion: acknowledge frustration, then steer anyway. Decide, articulate, advance.",
    "reversedLong": "Reversed, the Chariot warns of burnout, distraction, or chasing goals that no longer fit. Movement without direction leads to fatigue that feels like failure. Pause and re‑evaluate the map: is your destination still yours, or inherited from someone else’s expectations? Real control is the ability to redirect. Choose a truer aim and go again.",
    "promptUpright": "What single objective deserves your full drive this week?",
    "promptReversed": "What goal could you release to regain genuine motivation?”
  },
  {
    "key": "major_08",
    "name": "Strength (8)",
    "imgUpright": "images/major_08_u.jpg",
    "imgReversed": "images/major_08_r.jpg",
    "upright": "Traditional: courage, patience, gentle power. Inner reading: kindness tames what force provokes. Gentle prompt: Where can you greet fear with warmth and stay?",
    "reversed": "Traditional: self-doubt, fragility, harshness. Inner reading: inner critic is tired, not wise. Gentle prompt: What phrase would a loving friend offer you right now?",
    "uprightLong": "Strength speaks of resilience grounded in calm. It’s not about domination but about meeting fear with patience. Emotional regulation — steady breath, kind self‑talk, gentle persistence — tames chaos faster than force. When you hold your ground kindly, confidence grows from evidence, not hype. This card invites daily practices that anchor you in self‑respect: stretching, mindful breaks, honest boundaries. Courage is quiet and repeatable.",
    "reversedLong": "Reversed, Strength signals self‑criticism or exhaustion. You may feel weak because you’ve been battling too hard for too long. Courage now means rest, boundaries, and acceptance of limits. Power returns when kindness does. Let the inner critic nap; it’s not your motivator, just a tired guard. Choose restorative actions that prove you’re on your own side.",
    "promptUpright": "What gentle action today would remind you of your own capability?",
    "promptReversed": "How could you speak to yourself as you would to a beloved friend who’s worn out?"
  },
  {
    "key": "major_09",
    "name": "The Hermit (9)",
    "imgUpright": "images/major_09_u.jpg",
    "imgReversed": "images/major_09_r.jpg",
    "upright": "Traditional: introspection, wisdom, solitude. Inner reading: step out to step within. Gentle prompt: What small retreat (10 minutes) would help you hear your own voice?",
    "reversed": "Traditional: isolation, avoidance, withdrawal. Inner reading: alone has become hiding. Re-enter gently. Gentle prompt: Who is a safe person to share one honest sentence with?",
    "uprightLong": "The Hermit honors solitude as a tool, not a punishment. Pull back to analyze your direction and motives. Reflection brings efficiency — you stop solving the wrong problem. Journaling, meditation, or quiet study can clarify what no meeting ever could. True insight forms when stimulation drops. Withdraw long enough to realign your path with your inner truth, then re‑engage with intention.",
    "reversedLong": "Reversed, The Hermit points to isolation, cynicism, or burnout disguised as independence. If you’ve been carrying wisdom alone, share it; if you’ve been hiding, step out. Growth requires exchange. Balance introspection with connection so reflection turns into contribution. Ask for one conversation that invites you back into the world.",
    "promptUpright": "When was the last time silence taught you something useful?",
    "promptReversed": "What insight could you express aloud to someone who needs it too?”
  },
  {
    "key": "major_10",
    "name": "Wheel of Fortune (10)",
    "imgUpright": "images/major_10_u.jpg",
    "imgReversed": "images/major_10_r.jpg",
    "upright": "Traditional: cycles, luck, turning points. Inner reading: what’s changing is not random—participate. Gentle prompt: What tiny lever can you pull to meet the turning with grace?",
    "reversed": "Traditional: resistance to change, stagnation. Inner reading: clinging jams the wheel. Gentle prompt: What expectation can you release to let movement return?",
    "uprightLong": "The Wheel of Fortune teaches flexibility. Life shifts — success, failure, calm, chaos — but your power lies in adaptation. Upright, it signals a turning point or streak of synchronicity: patterns align when you respond instead of react. Notice timing, seize opportunities, and accept that change doesn’t owe explanation. Flow with it consciously; prepare, then say yes.",
    "reversedLong": "Reversed, the Wheel shows resistance to change or repeating cycles. You might be replaying an old lesson because you haven’t integrated it yet. Instead of blaming luck, examine patterns — what decision keeps resetting the game? Recognizing it is liberation. Growth resumes once accountability replaces frustration. Choose differently on purpose.",
    "promptUpright": "What new possibility is asking you to say “yes” before you feel ready?",
    "promptReversed": "What recurring situation is quietly asking for a different response this time?”
  },
  {
    "key": "major_11",
    "name": "Justice (11)",
    "imgUpright": "images/major_11_u.jpg",
    "imgReversed": "images/major_11_r.jpg",
    "upright": "Traditional: truth, fairness, cause/effect. Inner reading: integrity simplifies decisions. Gentle prompt: What is the honest fact you’re ready to act on?",
    "reversed": "Traditional: imbalance, denial, unfairness. Inner reading: avoidance has a cost. Repair is available. Gentle prompt: What small amends or boundary would restore balance?",
    "uprightLong": "Justice asks you to pause and assess fairness — not only toward others, but toward yourself. Upright, it represents accountability, balance, and transparency. Make decisions rooted in truth rather than habit. Sometimes the fairest outcome isn’t the easiest — it’s the one that restores integrity. If something feels off, it probably is. Gather facts, then act.",
    "reversedLong": "When reversed, Justice highlights bias, avoidance, or guilt clouding your clarity. You may be rationalizing rather than resolving. Step back, confront what you’ve postponed, and choose one specific corrective action. Even small acts of responsibility lift heavy emotional weight. Rebuild trust in your own judgment by following through.",
    "promptUpright": "What truth, once accepted, will make every future choice simpler?",
    "promptReversed": "What unfinished correction could lighten your conscience right now?"
  },
  {
    "key": "major_12",
    "name": "The Hanged Man (12)",
    "imgUpright": "images/major_12_u.jpg",
    "imgReversed": "images/major_12_r.jpg",
    "upright": "Traditional: surrender, new perspective, pause. Inner reading: not moving is the move. Gentle prompt: What can you release to see this from a kinder angle?",
    "reversed": "Traditional: stalling, martyrdom, stuckness. Inner reading: waiting has become avoiding. Gentle prompt: What decision would free your energy even if imperfect?",
    "uprightLong": "The Hanged Man represents stillness as strategy. By suspending immediate reaction, you open perspective. This pause allows new angles on an old issue — ones that movement would blur. Surrender here doesn’t mean defeat; it means patience while your understanding matures. Stop forcing the solution and let observation refine it. Sometimes waiting reveals that a problem doesn’t need solving at all.",
    "reversedLong": "Reversed, The Hanged Man signals stagnation — staying stuck long after insight has formed. Fear of change may disguise itself as ‘waiting for a sign.’ You already know what’s next; courage is the missing ingredient. Break inertia by choosing progress over perfection. Move with what you know.",
    "promptUpright": "Where might doing nothing for a day actually move things forward?",
    "promptReversed": "What one decision could release the tension of endless reflection?"
  },
  {
    "key": "major_13",
    "name": "Death (13)",
    "imgUpright": "images/major_13_u.jpg",
    "imgReversed": "images/major_13_r.jpg",
    "upright": "Traditional: endings, transformation, renewal. Inner reading: closing is a devotion to what’s alive. Gentle prompt: What are you lovingly finishing so new growth can begin?",
    "reversed": "Traditional: fear of change, stagnation, decay. Inner reading: you’re carrying what’s complete. Gentle prompt: What gentle goodbye would honor both what was and who you are now?",
    "uprightLong": "Death marks transformation disguised as ending. Something important — a project, relationship, belief — has completed its purpose. Mourning is natural, but staying attached traps energy meant for rebirth. Accept closure as compost: what decays feeds what’s next. Practically, this might mean letting go of a goal that no longer inspires or redefining success after loss. Renewal begins the moment you stop resisting change.",
    "reversedLong": "Reversed, Death points to avoidance of change. You might cling to comfort zones, delaying evolution. This is a slow suffocation — not tragedy, but hesitation. Choose transition intentionally rather than waiting for crisis to force it. The longer you resist, the heavier it becomes. Say goodbye kindly and step forward.",
    "promptUpright": "What chapter could you lovingly close to make space for something alive?",
    "promptReversed": "What would saying goodbye free you to welcome next?"
  },
  {
    "key": "major_14",
    "name": "Temperance (14)",
    "imgUpright": "images/major_14_u.jpg",
    "imgReversed": "images/major_14_r.jpg",
    "upright": "Traditional: harmony, moderation, integration. Inner reading: mix, don’t swing. Gentle prompt: What would 10% more balance look like today?",
    "reversed": "Traditional: excess, extremes, imbalance. Inner reading: the pendulum is tired. Gentle prompt: What is one middle step between too much and too little?",
    "uprightLong": "Temperance invites equilibrium. It’s the art of moderation: blending discipline with ease, work with rest, self with others. You progress fastest by balancing extremes, not swinging between them. Integrate lessons instead of reacting to them. Balance isn’t achieved once — it’s maintained daily. Small, consistent harmony beats dramatic overhaul. Adjust inputs and pace until calm returns.",
    "reversedLong": "Reversed, Temperance warns of excess or burnout. You may be overcommitted or swinging wildly between indulgence and deprivation. Check routines and emotional diet — are they nourishing or numbing you? Real balance often looks simpler than ego allows. Subtract something today and let steadiness reappear.",
    "promptUpright": "What adjustment would make your pace more sustainable this week?",
    "promptReversed": "What can you subtract today to return to calm effectiveness?"
  },
  {
    "key": "major_15",
    "name": "The Devil (15)",
    "imgUpright": "images/major_15_u.jpg",
    "imgReversed": "images/major_15_r.jpg",
    "upright": "Traditional: attachment, temptation, shadow patterns. Inner reading: you’re not trapped—the chain is unlatched. Gentle prompt: What comfort is costing you clarity, and how could you soothe differently?",
    "reversed": "Traditional: release, reclaiming power, detachment. Inner reading: the spell breaks when named. Gentle prompt: What tiny act of freedom could you gift yourself today?",
    "uprightLong": "The Devil illuminates attachment — habits, relationships, or mindsets you feel dependent on. It’s not inherently evil; it’s the pattern that once protected you but now restricts you. Awareness is the key to liberation. Identify the comfort that’s turned into a cage — consumption, control, comparison, or approval. Once named, its power weakens. Replace the habit with one that meets the same need in a healthier way. Freedom grows with every conscious choice.",
    "reversedLong": "Reversed, The Devil signals release — or the moment right before it. You’re seeing through illusions that kept you small. Freedom requires compassion: forgive the version of you who clung to survival mechanisms. Move forward without shame. Each aligned action breaks the old contract and strengthens trust in yourself."
    "promptUpright": "What recurring behavior feels good short-term but erodes peace long-term?",
    "promptReversed": "What tiny action could prove to yourself that you’re already freer than before?"
  },
  {
    "key": "major_16",
    "name": "The Tower (16)",
    "imgUpright": "images/major_16_u.jpg",
    "imgReversed": "images/major_16_r.jpg",
    "upright": "Traditional: upheaval, revelation, breakdown. Inner reading: truth clears false structures. Gentle prompt: What honesty would you rather face than keep balancing rubble?",
    "reversed": "Traditional: fear of change, delayed collapse. Inner reading: gentle demolition beats sudden shock. Gentle prompt: What can you dismantle kindly before it falls loudly?",
    "uprightLong": "The Tower represents necessary disruption — the collapse of what no longer serves truth. It’s the moment when denial can’t hold weight anymore. Though shocking, it’s liberation in disguise. When structures break, they make space for integrity. Let go of control and face change with open eyes. This might mean an emotional breakthrough, sudden realization, or ending you didn’t plan for. Accept the clarity that chaos offers — after the dust settles, what remains is real.",
    "reversedLong": "Reversed, the Tower suggests resistance to transformation or denial of a brewing problem. Avoiding small adjustments invites bigger shocks later. Choose conscious change instead of waiting for collapse. The discomfort you’re avoiding is temporary — the relief afterward is lasting. Make one voluntary change now."
    "promptUpright": "What truth are you now strong enough to face without defense?",
    "promptReversed": "What could you dismantle voluntarily before life does it for you?" 
  },
  {
    "key": "major_17",
    "name": "The Star (17)",
    "imgUpright": "images/major_17_u.jpg",
    "imgReversed": "images/major_17_r.jpg",
    "upright": "Traditional: hope, healing, openness. Inner reading: tenderness is strength. Gentle prompt: Where can you be 5% more receptive to support or grace?",
    "reversed": "Traditional: doubt, cynicism, dimmed faith. Inner reading: hope needs care, not proof. Gentle prompt: What tiny sign of life can you water today?",
    "uprightLong": "The Star signals healing, faith, and renewed optimism. After turmoil, hope returns — not naïve but informed. You’re reminded that vulnerability attracts restoration. Show your authentic self without editing for approval. This is a time for self‑compassion and gentle reconstruction: nourish your body, reconnect with inspiration, and practice gratitude in small acts. Healing isn’t linear, but every honest breath rebuilds confidence.",
    "reversedLong": "Reversed, the Star warns that discouragement or cynicism has dimmed your light. You may be focusing on evidence of failure instead of progress. Reconnect to purpose through gratitude journaling, movement, or art. Reignite faith through micro‑trust — noticing what is working. Light returns through attention, not waiting."
    "promptUpright": "What small kindness toward yourself could reopen your belief in possibility?",
    "promptReversed": "What would hope look like if it were quiet but steady?"
  },
  {
    "key": "major_18",
    "name": "The Moon (18)",
    "imgUpright": "images/major_18_u.jpg",
    "imgReversed": "images/major_18_r.jpg",
    "upright": "Traditional: dreams, intuition, the unknown. Inner reading: walk by feel; clarity is dawning. Gentle prompt: What feeling deserves a name before a plan?",
    "reversed": "Traditional: confusion lifting, fears examined. Inner reading: test the story with one fact. Gentle prompt: What assumption can you kindly verify?",
    "uprightLong": "The Moon invites you to explore uncertainty with curiosity. Your subconscious speaks through intuition, dreams, or emotions that don’t make linear sense. Don’t rush to decode them; just notice patterns. Confusion isn’t failure — it’s a sign that growth is happening below the surface. Create space for imagination and reflection, but keep grounding habits nearby. Trust gradual clarity.",
    "reversedLong": "Reversed, The Moon indicates emerging clarity — illusions are dissolving, revealing truth beneath fear. Yet, the process may feel disorienting. Ground yourself in routine while re‑evaluating assumptions. What you thought was danger might just be uncertainty. Distinguish intuition from anxiety through calm observation and small experiments."
    "promptUpright": "What emotion feels mysterious but deserves patient attention instead of judgment?",
    "promptReversed": "Which belief, once questioned, could restore your peace of mind?"
  },
  {
    "key": "major_19",
    "name": "The Sun (19)",
    "imgUpright": "images/major_19_u.jpg",
    "imgReversed": "images/major_19_r.jpg",
    "upright": "Traditional: joy, vitality, clarity. Inner reading: life wants to warm you. Gentle prompt: What simple pleasure could you allow without earning it first?",
    "reversed": "Traditional: temporary clouds, subdued optimism. Inner reading: the light is present but blocked. Gentle prompt: What small action would let more light in today?",
    "uprightLong": "The Sun radiates confidence, clarity, and vitality. It’s the moment you realize your joy doesn’t need justification. This card encourages full self‑expression — speak proudly, laugh loudly, live visibly. Success grows where authenticity shines without apology. Celebrate progress, however modest. Happiness strengthens resilience more than self‑criticism ever could. Choose activities that feel like sunshine to your system.",
    "reversedLong": "Reversed, The Sun reveals temporary dimness — fatigue, self‑doubt, or creative block. You may be underestimating your achievements or comparing your pace to others. Step into sunlight literally or metaphorically: movement, connection, or play. Reignite positivity through physical engagement, not thought. Joy returns when you act like it’s possible."
    "promptUpright": "What moment of lightness could you let yourself feel fully today?",
    "promptReversed": "What activity always brightens you, no matter your mood?"
  },
  {
    "key": "major_20",
    "name": "Judgement (20)",
    "imgUpright": "images/major_20_u.jpg",
    "imgReversed": "images/major_20_r.jpg",
    "upright": "Traditional: awakening, forgiveness, calling. Inner reading: answer the inner trumpet. Gentle prompt: What truth are you ready to rise to without punishing your past self?",
    "reversed": "Traditional: self-doubt, delay, harsh self-judgment. Inner reading: you don’t need a verdict to begin again. Gentle prompt: What compassionate reframe would let you step forward now?",
    "uprightLong": "Judgement marks awakening — seeing your life with new clarity and forgiving the past version of yourself. It’s a call to act on what you’ve learned, not just think about it. Self‑forgiveness transforms guilt into wisdom. Recognize how far you’ve come, then decide what the next evolution requires. Let go of regret; you can’t heal by punishing yourself. Answer the call with a specific, life‑affirming step.",
    "reversedLong": "Reversed, Judgement suggests hesitation to accept growth or guilt for changing. You may doubt you’re ready for a new stage or fear losing belonging by evolving. But staying small helps no one. Review lessons, acknowledge mistakes, then act. Redemption isn’t earned — it’s allowed. Choose the next right step and let it redefine you."
    "promptUpright": "What decision could honor who you’ve become rather than who you were?",
    "promptReversed": "What would forgiving yourself make space to begin?"
  },
  {
    "key": "major_21",
    "name": "The World (21)",
    "imgUpright": "images/major_21_u.jpg",
    "imgReversed": "images/major_21_r.jpg",
    "upright": "Traditional: completion, wholeness, integration. Inner reading: the cycle closes; you have become the lesson. Gentle prompt: What celebration or closure ritual would honor this finish?",
    "reversed": "Traditional: almost there, loose ends, delay. Inner reading: one stitch remains. Gentle prompt: What final tidy action would free you to begin the next chapter cleanly?",
    "uprightLong": "The World signifies completion, mastery, and integration. You’ve reached a milestone and can finally see the coherence behind past struggles. Celebrate the closure and the wisdom it brings. This is not an end but a pause before renewal — every ending seeds a new Fool’s journey. Recognize yourself as whole, not just achieving but understanding. Mark the moment so your body remembers it.",
    "reversedLong": "Reversed, The World suggests almost‑finished business or lingering doubt after success. You may minimize achievements or avoid closure out of fear of emptiness. Take time to acknowledge the finish — integration matters as much as ambition. Only then can new cycles begin cleanly. Do the last small thing that makes it complete."
    "promptUpright": "What ritual could help you honor how far you’ve come?",
    "promptReversed": "What would “done” look like if you let it feel complete?”*?
  },
  {
    "key": "wands_ace",
    "name": "Ace of Wands",
    "imgUpright": "images/wands_ace_u.jpg",
    "imgReversed": "images/wands_ace_r.jpg",
    "upright": "",
    "reversed": "",
    "uprightLong": "The Ace of Wands ignites your creative spark — the first pulse of motivation before planning kicks in. You might feel a surge of inspiration or an urge to begin something you can’t fully define yet. Don’t overthink the “how”; honor the “why.” Action, not clarity, will reveal form. Start a draft, a sketch, a message, anything that channels the spark before it fades. Passion is a renewable resource only when used.",
    "reversedLong": "Reversed, this card signals blocked enthusiasm or burnout. You might be waiting to *feel ready* again — but energy returns through movement, not rest alone. Revisit old interests; re-spark curiosity in small, non-pressured ways. Sometimes “stuck” just means overexerted.",
    "promptUpright": "What’s one idea you could act on before the excitement cools?",
    "promptReversed": "What small joy could rekindle your motivation today?"
  },
  {
    "key": "wands_02",
    "name": "Two of Wands",
    "imgUpright": "images/wands_02_u.jpg",
    "imgReversed": "images/wands_02_r.jpg",
    "upright": "",
    "reversed": "",
    "uprightLong": "This card marks planning and expanding perspective. You’ve moved beyond impulse — now it’s about structuring potential. Map your options, research next steps, but stay flexible. Vision becomes reality through grounded logistics, not fantasy. The key is balancing foresight with courage: make a decision, even if imperfect.",
    "reversedLong": "Reversed, the Two of Wands shows analysis paralysis or fear of leaving the comfort zone. You may over-plan to delay commitment. Accept that uncertainty is built into growth. You’ll learn more from iteration than hesitation.",
    "promptUpright": "What next step would turn your current idea into progress, not just possibility?",
    "promptReversed": "What would you risk missing by staying in place too long?"
  },
  {
    "key": "wands_03",
    "name": "Three of Wands",
    "imgUpright": "images/wands_03_u.jpg",
    "imgReversed": "images/wands_03_r.jpg",
    "upright": "",
    "reversed": "",
    "uprightLong": "The Three of Wands is expansion in motion — the moment when effort starts showing results. It encourages patience, delegation, and trust in timing. You’ve done your part; now let momentum carry you forward. Keep your vision alive but stop micromanaging outcomes.",
    "reversedLong": "Reversed, the card hints at frustration over delays or miscommunication. Progress may feel invisible, but foundations are still forming. Reconnect to your original motivation; persistence will outlast impatience.",
    "promptUpright": "Where could you replace control with confidence?",
    "promptReversed": "How can you support patience instead of fighting it?"
  },
  {
    "key": "wands_04",
    "name": "Four of Wands",
    "imgUpright": "images/wands_04_u.jpg",
    "imgReversed": "images/wands_04_r.jpg",
    "upright": "",
    "reversed": "",
    "uprightLong": "This card celebrates milestones and shared joy. Pause to acknowledge stability — your efforts created something solid. Gratitude fuels long-term growth. Celebration is not distraction; it’s reinforcement. Bring community into your success; belonging amplifies achievement.",
    "reversedLong": "Reversed, the Four of Wands shows tension within collaboration or difficulty accepting joy. Maybe you’re downplaying your success or overextending to keep harmony. Step back, redefine what “home” or “team” means now.",
    "promptUpright": "Who could you celebrate with to honor this progress fully?",
    "promptReversed": "What kind of environment truly lets you relax into yourself?"
  },
  {
    "key": "wands_05",
    "name": "Five of Wands",
    "imgUpright": "images/wands_05_u.jpg",
    "imgReversed": "images/wands_05_r.jpg",
    "upright": "",
    "reversed": "",
    "uprightLong": "Conflict sharpens awareness. The Five of Wands doesn’t mean chaos — it’s diversity of ideas demanding structure. Engage debate with curiosity instead of ego. Healthy friction can refine your goals if you listen actively.",
    "reversedLong": "Reversed, this card suggests avoiding confrontation or internal conflict. Peacekeeping at the cost of truth breeds resentment. Speak clearly and calmly — harmony follows honesty.",
    "promptUpright": "What disagreement could become productive if approached with openness?",
    "promptReversed": "What truth are you avoiding to keep temporary peace?"
  },
  {
    "key": "wands_06",
    "name": "Six of Wands",
    "imgUpright": "images/wands_06_u.jpg",
    "imgReversed": "images/wands_06_r.jpg",
    "upright": "",
    "reversed": "",
    "uprightLong": "Victory, recognition, and self-trust define this card. You’ve earned a moment of validation — let it sink in. Acknowledge your capability and express gratitude to those who helped. Confidence sustains success better than comparison.",
    "reversedLong": "Reversed, the Six of Wands warns of inflated ego or ignored achievements. Either you’re chasing validation or refusing it. Detach from approval; let internal pride replace external proof.",
    "promptUpright": "How can you celebrate yourself without needing applause?",
    "promptReversed": "What quiet win deserves your acknowledgment today?"
  },
  {
    "key": "wands_07",
    "name": "Seven of Wands",
    "imgUpright": "images/wands_07_u.jpg",
    "imgReversed": "images/wands_07_r.jpg",
    "upright": "",
    "reversed": "",
    "uprightLong": "The Seven of Wands is about holding your ground — advocating for your ideas without hostility. Boundaries are acts of clarity, not aggression. Defend your progress with calm conviction, not fear.",
    "reversedLong": "Reversed, this card suggests fatigue from constant guarding. Perhaps you’ve been in “fight mode” too long. It’s okay to rest; not every challenge requires battle. True strength includes surrender.",
    "promptUpright": "Where can you protect your focus without going on the defensive?",
    "promptReversed": "What can you stop defending that no longer threatens you?"
  },
  {
    "key": "wands_08",
    "name": "Eight of Wands",
    "imgUpright": "images/wands_08_u.jpg",
    "imgReversed": "images/wands_08_r.jpg",
    "upright": "",
    "reversed": "",
    "uprightLong": "Momentum is here. The Eight of Wands signals acceleration — messages, travel, rapid developments. Trust timing and respond promptly but mindfully. Don’t add resistance by overanalyzing flow. Channel the pace into focus, not frenzy.",
    "reversedLong": "Reversed, this card means delays or scattered attention. Slow progress doesn’t mean no progress. Use the pause to clarify priorities — you might be saved from rushing the wrong direction.",
    "promptUpright": "What quick action could keep you aligned while momentum builds?",
    "promptReversed": "What slowdown could actually serve your highest interest?"
  },
  {
    "key": "wands_09",
    "name": "Nine of Wands",
    "imgUpright": "images/wands_09_u.jpg",
    "imgReversed": "images/wands_09_r.jpg",
    "upright": "",
    "reversed": "",
    "uprightLong": "Perseverance is the theme. You’ve endured setbacks but still stand capable. Strength now is strategic, not stubborn — protect your progress while pacing energy. Rest when needed; resilience is maintenance, not martyrdom.",
    "reversedLong": "Reversed, the card signals burnout or paranoia. Fatigue may distort perception — not every challenge is a threat. Step back, rest, and reassess. Courage without recovery collapses.",
    "promptUpright": "What support could turn endurance into ease?",
    "promptReversed": "What boundary could prevent exhaustion from repeating?"
  },
  {
    "key": "wands_10",
    "name": "Ten of Wands",
    "imgUpright": "images/wands_10_u.jpg",
    "imgReversed": "images/wands_10_r.jpg",
    "upright": "",
    "reversed": "",
    "uprightLong": "Responsibility and accomplishment coexist here. You’ve taken on much — perhaps too much — but this load has taught efficiency. Delegation isn’t weakness; it’s wisdom. Drop unnecessary burdens and keep only what serves purpose.",
    "reversedLong": "Reversed, the card indicates overload or emotional fatigue. You might be defining worth by productivity. Simplify commitments before resentment replaces purpose.",
    "promptUpright": "Which obligation could you release to move lighter?",
    "promptReversed": "What task could you postpone or share to reclaim balance?"
  },
  {
    "key": "wands_page",
    "name": "Page of Wands",
    "imgUpright": "images/wands_page_u.jpg",
    "imgReversed": "images/wands_page_r.jpg",
    "upright": "",
    "reversed": "",
    "uprightLong": "The Page of Wands brings a rush of curiosity and possibility. You’re in beginner’s mind — the sweet spot between excitement and inexperience. This is your cue to explore, test, and make mistakes fast. Let discovery replace pressure; enthusiasm is the spark that sustains long projects. Be playful with creativity instead of chasing perfection. The key lesson: learning is momentum, not delay.",
    "reversedLong": "Reversed, this Page warns of restlessness and scattered focus. You may chase stimulation over purpose or drop ideas at the first obstacle. Revisit your “why,” simplify inputs, and channel curiosity into a single direction. Inspiration multiplies when contained.",
    "promptUpright": "What small experiment would feel fun even if it fails?",
    "promptReversed": "What idea deserves completion instead of replacement?"
  },
  {
    "key": "wands_knight",
    "name": "Knight of Wands",
    "imgUpright": "images/wands_knight_u.jpg",
    "imgReversed": "images/wands_knight_r.jpg",
    "upright": "",
    "reversed": "",
    "uprightLong": "This Knight charges ahead with confidence and passion. It’s your call to act boldly and trust instinct. Progress now rewards courage, not caution. However, enthusiasm needs aim — excitement without purpose burns energy. Direct momentum with intention, and you’ll turn sparks into steady fire.",
    "reversedLong": "Reversed, the Knight of Wands burns out chasing every spark. Impulse and boredom rotate like seasons. Slow down to reconnect action with purpose. Pause doesn’t mean failure — it’s recalibration.",
    "promptUpright": "Where can you act decisively without waiting for certainty?",
    "promptReversed": "What part of your routine could you steady to protect your passion?"
  },
  {
    "key": "wands_queen",
    "name": "Queen of Wands",
    "imgUpright": "images/wands_queen_u.jpg",
    "imgReversed": "images/wands_queen_r.jpg",
    "upright": "",
    "reversed": "",
    "uprightLong": "The Queen of Wands embodies radiant confidence. She creates through charisma, not force. You’re invited to express yourself authentically, lead through enthusiasm, and own your presence. Magnetism grows when you believe in your worth. Make visibility an act of service, not vanity — your light reminds others of theirs.",
    "reversedLong": "Reversed, this Queen signals self-doubt or creative dimming. You may shrink to avoid judgment. Reconnect with what energizes you privately first; warmth returns before spotlight. Self-trust rekindles influence.",
    "promptUpright": "Where can you take up space with ease instead of apology?",
    "promptReversed": "What environment helps you remember your natural confidence?"
  },
  {
    "key": "wands_king",
    "name": "King of Wands",
    "imgUpright": "images/wands_king_u.jpg",
    "imgReversed": "images/wands_king_r.jpg",
    "upright": "",
    "reversed": "",
    "uprightLong": "The King of Wands leads through vision. You’ve gained enough experience to guide others by example, not command. Empower, delegate, and inspire — your fire multiplies when shared. Visionary leadership isn’t about control but coherence: aligning purpose with action.",
    "reversedLong": "Reversed, the King warns against ego-driven direction. Pride, impatience, or micromanagement can extinguish teamwork. Reconnect with purpose and humility; your power is influence, not dominance.",
    "promptUpright": "Whose spark could you ignite through your guidance today?",
    "promptReversed": "What would trusting others to rise beside you make possible?"
  },
  {
    "key": "cups_ace",
    "name": "Ace of Cups",
    "imgUpright": "images/cups_ace_u.jpg",
    "imgReversed": "images/cups_ace_r.jpg",
    "upright": "",
    "reversed": "",
    "uprightLong": "The Ace of Cups overflows with emotional renewal and openness. Love, forgiveness, and creativity stem from vulnerability. This is the heart’s reset button. Express affection freely, journal your gratitude, or allow tears that cleanse. Let empathy refill your emotional reserves.",
    "reversedLong": "Reversed, the Ace points to emotional blockage or suppression. Perhaps self-protection has turned into isolation. Reconnection begins with self-kindness — acknowledge the feeling without fixing it. Healing follows honesty.",
    "promptUpright": "What emotion deserves honest expression today?",
    "promptReversed": "What would happen if you allowed yourself to feel without labeling it wrong?"
  },
  {
    "key": "cups_02",
    "name": "Two of Cups",
    "imgUpright": "images/cups_02_u.jpg",
    "imgReversed": "images/cups_02_r.jpg",
    "upright": "",
    "reversed": "",
    "uprightLong": "This card celebrates mutual respect and partnership. Collaboration thrives when communication stays clear and generous. Whether romantic, platonic, or professional, shared growth requires reciprocity. Honor equality by listening as much as you speak.",
    "reversedLong": "Reversed, imbalance or miscommunication disturbs harmony. You might be giving more than you receive or avoiding honesty to preserve peace. Healthy connection can handle truth — real unity needs transparency.",
    "promptUpright": "What relationship could deepen through one sincere act of appreciation?",
    "promptReversed": "What boundary could restore balance in connection?"
  },
  {
    "key": "cups_03",
    "name": "Three of Cups",
    "imgUpright": "images/cups_03_u.jpg",
    "imgReversed": "images/cups_03_r.jpg",
    "upright": "",
    "reversed": "",
    "uprightLong": "The Three of Cups symbolizes community and joy. Connection is medicine; celebrate life with people who replenish you. Share achievements, laughter, or gratitude. Emotional resilience strengthens through togetherness.",
    "reversedLong": "Reversed, it may suggest social fatigue or performing belonging. Step back from shallow circles and nurture depth instead. Joy returns when authenticity replaces obligation.",
    "promptUpright": "Who could you thank or celebrate with this week?",
    "promptReversed": "Who truly makes you feel at home in yourself?"
  },
  {
    "key": "cups_04",
    "name": "Four of Cups",
    "imgUpright": "images/cups_04_u.jpg",
    "imgReversed": "images/cups_04_r.jpg",
    "upright": "",
    "reversed": "",
    "uprightLong": "This card appears when apathy clouds awareness. You may feel detached from daily joy. Instead of chasing excitement, look for gratitude in the ordinary. Contentment grows from noticing, not acquiring.",
    "reversedLong": "Reversed, the heart stirs again — curiosity and openness begin returning. Follow mild interest before passion fully awakens. Growth doesn’t need drama; it needs permission.",
    "promptUpright": "What small detail could you appreciate right now?",
    "promptReversed": "What simple curiosity feels like a quiet yes?"
  },
  {
    "key": "cups_05",
    "name": "Five of Cups",
    "imgUpright": "images/cups_05_u.jpg",
    "imgReversed": "images/cups_05_r.jpg",
    "upright": "",
    "reversed": "",
    "uprightLong": "Grief and disappointment are natural; the Five of Cups teaches acceptance without collapse. Focus gently on what remains rather than what’s gone. Loss, when processed, clarifies value. Let yourself feel, but don’t mistake sadness for the whole story.",
    "reversedLong": "Reversed, this card signals emotional recovery. Perspective widens; you see lessons where only pain existed. Healing becomes a choice. Turn attention toward gratitude and growth — they’re ready.",
    "promptUpright": "What remains standing that still supports you?",
    "promptReversed": "What insight did loss gift you?"
  },
  {
    "key": "cups_06",
    "name": "Six of Cups",
    "imgUpright": "images/cups_06_u.jpg",
    "imgReversed": "images/cups_06_r.jpg",
    "upright": "",
    "reversed": "",
    "uprightLong": "Nostalgia softens the present. Reconnecting with your inner child or past kindness can restore joy and innocence. Use memory as medicine, not escape — let good moments remind you what’s worth protecting.",
    "reversedLong": "Reversed, the Six warns against living through memory. Over-idealizing the past can block the present. Integrate lessons without regression. Gratitude belongs to yesterday; purpose lives today.",
    "promptUpright": "What old joy could you revive in a new way?",
    "promptReversed": "What comfort from the past can inspire, not imprison, you now?"
  },
  {
    "key": "cups_07",
    "name": "Seven of Cups",
    "imgUpright": "images/cups_07_u.jpg",
    "imgReversed": "images/cups_07_r.jpg",
    "upright": "",
    "reversed": "",
    "uprightLong": "The Seven of Cups reflects imagination and choice — a landscape of possibilities, some inspiring, others distracting. When everything looks appealing, clarity hides behind emotion. Take inventory: which option energizes, which drains? Not every opportunity is yours to pursue. Daydreams become direction when filtered through values.",
    "reversedLong": "Reversed, confusion clears. You’re seeing through illusion, distinguishing fantasy from feasible vision. Now is the time to commit — choosing doesn’t limit freedom, it focuses it. Simplify your choices into one aligned action.",
    "promptUpright": "Which idea feels exciting *and* sustainable?",
    "promptReversed": "What decision would release mental clutter?"
  },
  {
    "key": "cups_08",
    "name": "Eight of Cups",
    "imgUpright": "images/cups_08_u.jpg",
    "imgReversed": "images/cups_08_r.jpg",
    "upright": "",
    "reversed": "",
    "uprightLong": "The Eight of Cups honors the courage to walk away from what no longer fulfills. Leaving isn’t failure; it’s evolution. You’ve outgrown an emotional environment or pursuit — acknowledge gratitude, then move on. Growth requires releasing the known to find meaning anew.",
    "reversedLong": "Reversed, this card shows hesitation — knowing it’s time to move, yet lingering. Fear of regret can freeze progress. Trust that intuition’s whisper is enough reason. Departure may ache, but stagnation aches longer.",
    "promptUpright": "What part of your life feels complete enough to release with love?",
    "promptReversed": "What reassurance could you offer yourself to take that first step?"
  },
  {
    "key": "cups_09",
    "name": "Nine of Cups",
    "imgUpright": "images/cups_09_u.jpg",
    "imgReversed": "images/cups_09_r.jpg",
    "upright": "",
    "reversed": "",
    "uprightLong": "The Nine of Cups embodies contentment and personal fulfillment. It’s a reminder to appreciate success before chasing the next goal. You’ve created satisfaction; let it sink in. Gratitude turns accomplishment into emotional wealth. Celebrate quietly, without conditions.",
    "reversedLong": "Reversed, the card suggests overindulgence or hollow achievement. You might be using pleasure to avoid emptiness. Refocus on meaning, not image — fulfillment is sustainable when aligned with purpose.",
    "promptUpright": "How can you enjoy what you already have, without adding anything?",
    "promptReversed": "What’s missing beneath the surface of comfort?"
  },
  {
    "key": "cups_10",
    "name": "Ten of Cups",
    "imgUpright": "images/cups_10_u.jpg",
    "imgReversed": "images/cups_10_r.jpg",
    "upright": "",
    "reversed": "",
    "uprightLong": "Harmony and belonging define this card. The Ten of Cups shows emotional maturity — relationships or communities built on respect. You’re aligned with your values, and peace follows. Enjoy stability without fearing its end.",
    "reversedLong": "Reversed, unrealistic ideals or unspoken expectations disturb happiness. Joy becomes fragile when compared to perfection. Focus on presence rather than performance; wholeness is imperfect but real.",
    "promptUpright": "What daily action nurtures long-term harmony in your circle?",
    "promptReversed": "What standard of “happiness” can you release to feel content again?"
  },
  {
    "key": "cups_page",
    "name": "Page of Cups",
    "imgUpright": "images/cups_page_u.jpg",
    "imgReversed": "images/cups_page_r.jpg",
    "upright": "",
    "reversed": "",
    "uprightLong": "Curiosity, intuition, and play lead the Page of Cups. You’re learning emotional fluency — understanding feelings before acting on them. Let imagination guide problem-solving and connection. Sensitivity here is intelligence, not weakness.",
    "reversedLong": "Reversed, sensitivity tilts into escapism. Fantasy or self-pity blocks growth. Re-anchor through small, tangible acts of self-care — a walk, music, writing. Emotional maturity develops through presence, not retreat.",
    "promptUpright": "How could creativity express what words can’t today?",
    "promptReversed": "What soothing ritual grounds you back in reality gently?"
  },
  {
    "key": "cups_knight",
    "name": "Knight of Cups",
    "imgUpright": "images/cups_knight_u.jpg",
    "imgReversed": "images/cups_knight_r.jpg",
    "upright": "",
    "reversed": "",
    "uprightLong": "The Knight of Cups acts on beauty and empathy. You’re invited to pursue what inspires — a cause, connection, or creative goal. Lead through emotional intelligence; sincerity attracts allies. Keep ideals high, but balance with follow-through.",
    "reversedLong": "Reversed, moodiness or avoidance may replace genuine inspiration. You might be chasing validation instead of authentic feeling. Recenter through consistent effort; discipline protects dreams.",
    "promptUpright": "What heartfelt pursuit deserves your focus this month?",
    "promptReversed": "What habit could turn inspiration into tangible progress?"
  },
  {
    "key": "cups_queen",
    "name": "Queen of Cups",
    "imgUpright": "images/cups_queen_u.jpg",
    "imgReversed": "images/cups_queen_r.jpg",
    "upright": "",
    "reversed": "",
    "uprightLong": "The Queen embodies empathy and emotional maturity. She listens without absorbing others’ pain. This is your reminder that compassion thrives alongside boundaries. Nurture yourself so you can nurture others sustainably.",
    "reversedLong": "Reversed, emotional overwhelm or codependency clouds judgment. Detach kindly; your worth isn’t measured by caretaking. Refill before offering.",
    "promptUpright": "What self-care practice replenishes your ability to care?",
    "promptReversed": "How can you protect your peace without guilt?"
  },
  {
    "key": "cups_king",
    "name": "King of Cups",
    "imgUpright": "images/cups_king_u.jpg",
    "imgReversed": "images/cups_king_r.jpg",
    "upright": "",
    "reversed": "",
    "uprightLong": "Emotional steadiness defines this King. He leads calmly, mediating with empathy and clarity. You’re encouraged to hold authority without losing kindness — be the calm in others’ storms.",
    "reversedLong": "Reversed, this King suppresses emotions or manipulates subtly. Control can’t replace connection. Honest expression rebuilds trust inward and outward.",
    "promptUpright": "Where could your composure inspire stability in others?",
    "promptReversed": "What truth could you share to clear unspoken tension?"
  },
  {
    "key": "swords_ace",
    "name": "Ace of Swords",
    "imgUpright": "images/swords_ace_u.jpg",
    "imgReversed": "images/swords_ace_r.jpg",
    "upright": "",
    "reversed": "",
    "uprightLong": "Breakthrough and mental clarity. The Ace of Swords cuts through confusion — say what’s true, even if messy. Clear language frees energy stuck in rumination. Insight matters only when expressed.",
    "reversedLong": "Reversed, fog, indecision, or misinformation cloud your vision. Pause communication until clarity returns. Seek facts, not reassurance. Silence can sharpen thought.",
    "promptUpright": "What truth needs words instead of worry?",
    "promptReversed": "What assumption could you recheck before deciding?"
  },
  {
    "key": "swords_02",
    "name": "Two of Swords",
    "imgUpright": "images/swords_02_u.jpg",
    "imgReversed": "images/swords_02_r.jpg",
    "upright": "",
    "reversed": "",
    "uprightLong": "You’re at a crossroads. Avoiding a decision keeps anxiety alive. Choose awareness over avoidance: gather data, trust intuition, and commit. Peace comes after choice, not before.",
    "reversedLong": "Reversed, overwhelm or denial deepens the stalemate. You’re thinking in circles — pause the loop. Even a temporary choice builds momentum.",
    "promptUpright": "What information or feeling would make this decision easier?",
    "promptReversed": "What’s one small move that breaks indecision’s hold?"
  },
  {
    "key": "swords_03",
    "name": "Three of Swords",
    "imgUpright": "images/swords_03_u.jpg",
    "imgReversed": "images/swords_03_r.jpg",
    "upright": "",
    "reversed": "",
    "uprightLong": "Pain acknowledged is pain released. This card shows heartbreak, disappointment, or betrayal asking to be witnessed. Expression — writing, talking, crying — transforms suffering into clarity. Healing begins when you stop minimizing your hurt.",
    "reversedLong": "Reversed, healing has begun. Forgiveness — especially toward yourself — completes closure. Don’t rush; gentleness keeps scars flexible. You’re stronger for having felt deeply.",
    "promptUpright": "What emotion are you ready to name out loud?",
    "promptReversed": "What act of grace could honor how far you’ve healed?"
  },
  {
    "key": "swords_04",
    "name": "Four of Swords",
    "imgUpright": "images/swords_04_u.jpg",
    "imgReversed": "images/swords_04_r.jpg",
    "upright": "",
    "reversed": "",
    "uprightLong": "Rest and recalibration define this card. Mental fatigue means you’ve processed enough — now the mind needs silence. Prioritize recovery without guilt. Stillness prepares clarity’s return.",
    "reversedLong": "Reversed, exhaustion turns chronic. If you’re restless but drained, slow down strategically. Real productivity begins after repair. Rest isn’t earned — it’s required.",
    "promptUpright": "What rest would make your next effort more effective?",
    "promptReversed": "What signal has your body given that you’ve ignored?"
  },
  {
    "key": "swords_05",
    "name": "Five of Swords",
    "imgUpright": "images/swords_05_u.jpg",
    "imgReversed": "images/swords_05_r.jpg",
    "upright": "",
    "reversed": "",
    "uprightLong": "The Five of Swords signals the aftermath of conflict — the quiet after words cut too sharply. You may have won an argument but lost connection. This card reminds you that being “right” can sometimes mean being lonely. Pause and examine whether victory served truth or ego. In professional or personal life, progress now lies in reconciliation, not retaliation. Practically, that may mean offering an apology, clarifying intent, or simply dropping the need for the last word. The energy asks for maturity: trade pride for peace and you’ll feel the release immediately.",
    "reversedLong": "Reversed, the conflict is dissolving — forgiveness and understanding become possible. You’ve learned that communication without compassion breeds tension. This is your cue to rebuild trust through transparency and empathy. Don’t fix everything; repair what matters most. When you release resentment, energy returns to creation.",
    "promptUpright": "What outcome would feel better than being right?",
    "promptReversed": "What bridge could you quietly start rebuilding today?"
  },
  {
    "key": "swords_06",
    "name": "Six of Swords",
    "imgUpright": "images/swords_06_u.jpg",
    "imgReversed": "images/swords_06_r.jpg",
    "upright": "",
    "reversed": "",
    "uprightLong": "The Six of Swords represents transition and healing through movement. You’re leaving turbulence behind — maybe mentally, emotionally, or geographically. It’s not escape; it’s progression. Allow yourself distance from what drains clarity. The journey might feel uncertain, but peace accumulates with each mile of perspective. Detach gently from the past while carrying only its wisdom. In practical terms, this might mean changing environments, adjusting routines, or limiting contact with chaos. Every act that moves you toward calm counts.",
    "reversedLong": "Reversed, you may be resisting closure, replaying old narratives that keep pain current. The ferry waits, but hesitation delays relief. Accept that you can’t rewrite the past — you can only choose not to relive it. Gather your courage and row toward healing, even slowly. Progress is measured by honesty, not speed.",
    "promptUpright": "What change of scenery — literal or mental — would lighten your mind?",
    "promptReversed": "What story are you ready to stop retelling to find peace?"
  },
  {
    "key": "swords_07",
    "name": "Seven of Swords",
    "imgUpright": "images/swords_07_u.jpg",
    "imgReversed": "images/swords_07_r.jpg",
    "upright": "",
    "reversed": "",
    "uprightLong": "The Seven of Swords deals with strategy, discretion, and sometimes avoidance. It asks you to examine motives — yours and others’. Are you being resourceful or evasive? Smart planning protects energy, but secrecy breeds distance. Integrity is efficiency; deception is a leak. In work, choose quiet preparation over shortcuts. In relationships, clarity prevents confusion. The mature use of this energy is thoughtful communication paired with self-protection.",
    "reversedLong": "Reversed, truth surfaces. What was hidden seeks resolution. You may feel relief or vulnerability — both cleanse the air. Admission, even silent acknowledgment, ends the mental spin. This is accountability as freedom: releasing the weight of pretending. After confession, trust rebuilds naturally.",
    "promptUpright": "How can you stay strategic without sacrificing honesty?",
    "promptReversed": "What truth could free your energy if said aloud?"
  },
  {
    "key": "swords_08",
    "name": "Eight of Swords",
    "imgUpright": "images/swords_08_u.jpg",
    "imgReversed": "images/swords_08_r.jpg",
    "upright": "",
    "reversed": "",
    "uprightLong": "The Eight of Swords mirrors self-imposed limitation. You feel trapped, but the exit exists — obscured by fear and habit. The ropes are thoughts, not walls. Start by challenging one assumption: “I can’t because…” Replace it with curiosity: “What if I could in one small way?” Freedom begins in mental rehearsal, then physical motion. Observe the inner critic with distance; it guards outdated safety rules. Each brave thought loosens a knot.",
    "reversedLong": "Reversed, clarity dawns — you’re recognizing self-created barriers and dismantling them. It’s liberation through awareness. Continue small, consistent actions that prove capability to yourself. Independence is built moment by moment; confidence follows evidence. Celebrate every escape from doubt.",
    "promptUpright": "What belief keeps you still, and how could you gently test its truth?",
    "promptReversed": "What tiny action today would confirm your freedom is real?"
  },
  {
    "key": "swords_09",
    "name": "Nine of Swords",
    "imgUpright": "images/swords_09_u.jpg",
    "imgReversed": "images/swords_09_r.jpg",
    "upright": "",
    "reversed": "",
    "uprightLong": "This card embodies anxiety’s night hours — rumination, what-ifs, imagined catastrophes. The mind overprotects by rehearsing pain. The cure isn’t suppression but compassion: breathe, write worries down, externalize them so they shrink to scale. Anxiety loses grip when observed kindly. Practical care — hydration, daylight, conversation — grounds the nervous system back in present safety. Your fears want reassurance, not logic.",
    "reversedLong": "Reversed, dawn breaks. Perspective returns after sleepless worry. You’re starting to differentiate concern from reality. Maintain the practices that soothe — consistent rest, boundaries with news or screens, honest talk. Healing from fear is repetition of calm.",
    "promptUpright": "What evidence of safety can you remind yourself of right now?",
    "promptReversed": "What evening ritual could teach your body that the day is over?"
  },
  {
    "key": "swords_10",
    "name": "Ten of Swords",
    "imgUpright": "images/swords_10_u.jpg",
    "imgReversed": "images/swords_10_r.jpg",
    "upright": "",
    "reversed": "",
    "uprightLong": "Rock bottom becomes solid ground here. The Ten of Swords marks the end of an exhausting cycle — betrayal, burnout, or harsh truth. The mind has exhausted its defenses, leaving space for renewal. Allow closure instead of seeking more evidence. Acceptance is resurrection’s prelude. Practically, this means stepping back, redefining roles, or releasing perfectionism. The worst has already peaked; now healing begins quietly.",
    "reversedLong": "Reversed, recovery accelerates. You’re standing again, humbled but wiser. Integrate the lesson, not the pain. Don’t fear vulnerability; it proves you’re still open to life. Each sunrise after collapse rebuilds strength with more compassion.",
    "promptUpright": "What situation can you finally stop analyzing and simply let end?",
    "promptReversed": "What new boundary will protect the peace you’ve reclaimed?"
  },
  {
    "key": "swords_page",
    "name": "Page of Swords",
    "imgUpright": "images/swords_page_u.jpg",
    "imgReversed": "images/swords_page_r.jpg",
    "upright": "",
    "reversed": "",
    "uprightLong": "Curiosity fuels mental growth. The Page of Swords encourages study, dialogue, and asking better questions. You’re absorbing information fast — verify before sharing. Use your intellect to clarify, not impress. Observe communication patterns; listening sharpens thinking.",
    "reversedLong": "Reversed, scattered thoughts or defensiveness interrupt learning. You may be reacting rather than reasoning. Slow the tempo; reflect before responding. Intellectual humility creates connection where argument builds walls.",
    "promptUpright": "What topic genuinely excites your learning mind today?",
    "promptReversed": "What question could replace your next assumption?"
  },
  {
    "key": "swords_knight",
    "name": "Knight of Swords",
    "imgUpright": "images/swords_knight_u.jpg",
    "imgReversed": "images/swords_knight_r.jpg",
    "upright": "",
    "reversed": "",
    "uprightLong": "Focused ambition propels you. The Knight of Swords acts quickly on conviction. Channel this surge into a mission worth effort, but temper speed with awareness — urgency without empathy bruises progress. Aim your drive through a clear ethical filter.",
    "reversedLong": "Reversed, impatience or tunnel vision causes friction. Pause before reacting. Rushing drains credibility and results. Strategy beats force every time. Breathe, then proceed with clarity.",
    "promptUpright": "Where can swift action serve truth, not ego?",
    "promptReversed": "What would slowing down reveal that speed hides?"
  },
  {
    "key": "swords_queen",
    "name": "Queen of Swords",
    "imgUpright": "images/swords_queen_u.jpg",
    "imgReversed": "images/swords_queen_r.jpg",
    "upright": "",
    "reversed": "",
    "uprightLong": "The Queen embodies perceptive clarity. She separates emotion from evidence without dismissing either. Practice discernment: hear facts fully before concluding. Communicate honestly yet kindly — sharp words heal when delivered with grace. Objectivity is compassion wearing boundaries.",
    "reversedLong": "Reversed, intellect defends against vulnerability. Sarcasm, cynicism, or withdrawal may mask hurt. Allow warmth back into logic. Softening doesn’t weaken intelligence; it humanizes it.",
    "promptUpright": "What truth could you phrase more gently but still firmly?",
    "promptReversed": "Where could empathy make your reasoning stronger?"
  },
  {
    "key": "swords_king",
    "name": "King of Swords",
    "imgUpright": "images/swords_king_u.jpg",
    "imgReversed": "images/swords_king_r.jpg",
    "upright": "",
    "reversed": "",
    "uprightLong": "The King of Swords channels wisdom through structure. You’re called to make a decision using reason balanced with integrity. Define principles clearly and stand by them. Leadership now means fairness, not favoritism. Detachment clarifies, but compassion must remain at the helm.",
    "reversedLong": "Reversed, logic becomes manipulation or rigidity. You might use intellect to dominate rather than guide. Reconnect with purpose: truth serves, it doesn’t control. Apologize quickly if you’ve cut instead of clarified.",
    "promptUpright": "What principle will guide your next decision when emotions blur?",
    "promptReversed": "How could humility return balance to your authority?"
  },
  {
    "key": "pentacles_ace",
    "name": "Ace of Pentacles",
    "imgUpright": "images/pentacles_ace_u.jpg",
    "imgReversed": "images/pentacles_ace_r.jpg",
    "upright": "",
    "reversed": "",
    "uprightLong": "Opportunity is materializing. The Ace of Pentacles marks tangible beginnings — a job, project, or lifestyle upgrade. Ground ideas into routine: budgets, schedules, habits. Prosperity starts with consistent care of small details. Gratitude and stewardship attract expansion.",
    "reversedLong": "Reversed, missed chances or fear of scarcity may dominate. Redirect focus from outcome to preparation. Create the stability you crave through daily reliability. Wealth follows trust in process.",
    "promptUpright": "What practical step could anchor your new opportunity today?",
    "promptReversed": "How can you treat consistency itself as abundance?"
  },
  {
    "key": "pentacles_02",
    "name": "Two of Pentacles",
    "imgUpright": "images/pentacles_02_u.jpg",
    "imgReversed": "images/pentacles_02_r.jpg",
    "upright": "",
    "reversed": "",
    "uprightLong": "Balance and adaptability define this card. You’re managing multiple demands — progress depends on rhythm, not rigidity. Use planning tools, but stay playful. Flexibility prevents fatigue. Think dance, not juggle.",
    "reversedLong": "Reversed, imbalance leads to chaos or overwhelm. You may be saying yes too often. Prioritize essentials, drop guilt, and automate where possible. Stability grows when you stop rescuing every task.",
    "promptUpright": "What system could simplify your week without killing spontaneity?",
    "promptReversed": "What could you kindly postpone to breathe easier?"
  },
  {
    "key": "pentacles_03",
    "name": "Three of Pentacles",
    "imgUpright": "images/pentacles_03_u.jpg",
    "imgReversed": "images/pentacles_03_r.jpg",
    "upright": "",
    "reversed": "",
    "uprightLong": "Collaboration and skill-building shine. The Three of Pentacles rewards teamwork rooted in respect. Seek feedback; mastery matures in dialogue. Recognize your part in a larger structure — contribution is creation. Shared success multiplies motivation.",
    "reversedLong": "Reversed, miscommunication or ego may undermine cooperation. If progress stalls, revisit shared goals and clarify roles. Listen before fixing. Harmony rebuilds through humility.",
    "promptUpright": "Whose perspective could refine your current project?",
    "promptReversed": "What expectation needs to be voiced clearly to restore flow?"
  },
  {
    "key": "pentacles_04",
    "name": "Four of Pentacles",
    "imgUpright": "images/pentacles_04_u.jpg",
    "imgReversed": "images/pentacles_04_r.jpg",
    "upright": "",
    "reversed": "",
    "uprightLong": "The Four of Pentacles represents stability — and the instinct to guard it. You’ve worked hard to create security, but control easily turns into constriction. This card invites you to review what you’re holding too tightly: time, money, love, or opinions. Saving energy is wise; hoarding it breeds fear. True stability breathes. Generosity and circulation keep abundance alive. Let resources, creativity, and affection move through you like air in a well-ventilated room. Security grows by trust, not tension.",
    "reversedLong": "Reversed, the walls of protection have become isolation. Scarcity thinking drains more than it preserves. Re-enter exchange: donate, collaborate, or delegate. Every release teaches faith in replenishment. Hoarded energy stagnates; shared energy multiplies.",
    "promptUpright": "What could you share today that would make you feel lighter, not poorer?",
    "promptReversed": "Where could generosity reopen your sense of flow?"
  },
  {
    "key": "pentacles_05",
    "name": "Five of Pentacles",
    "imgUpright": "images/pentacles_05_u.jpg",
    "imgReversed": "images/pentacles_05_r.jpg",
    "upright": "",
    "reversed": "",
    "uprightLong": "This card portrays struggle, financial or emotional, but its message is belonging despite hardship. You may feel excluded or unsupported, yet help exists within reach if pride softens. Ask, communicate, let others in. Connection is part of survival strategy. On a practical level, review resources honestly and seek guidance; improvement begins with acknowledgment, not shame. Compassion for yourself keeps dignity intact through difficult seasons.",
    "reversedLong": "Reversed, recovery begins. Support arrives when you accept it. Mindset shifts from “lack” to “learning.” Even small improvements—steady work, gratitude, self-care—compound into stability. You’re walking out of scarcity; keep noticing evidence of safety.",
    "promptUpright": "Whose warmth or wisdom could you reach for instead of enduring alone?",
    "promptReversed": "What sign already proves that circumstances are improving?"
  },
  {
    "key": "pentacles_06",
    "name": "Six of Pentacles",
    "imgUpright": "images/pentacles_06_u.jpg",
    "imgReversed": "images/pentacles_06_r.jpg",
    "upright": "",
    "reversed": "",
    "uprightLong": "Giving and receiving come into balance. This card reminds you that generosity and boundaries coexist. Offer what you can without debt to yourself, and receive aid without guilt. Exchange—money, time, feedback—thrives when transparent. Equality, not hierarchy, keeps relationships healthy. In leadership, practice fair distribution of credit and reward. In friendship, let help circulate both ways.",
    "reversedLong": "Reversed, imbalance surfaces: over-giving, dependency, or transactional kindness. Reflect on motive—are you giving to connect or to control? Sustainable generosity requires reciprocity. Adjust flow, not feeling.",
    "promptUpright": "Where could balanced generosity strengthen trust today?",
    "promptReversed": "What boundary could protect the purity of your giving?"
  },
  {
    "key": "pentacles_07",
    "name": "Seven of Pentacles",
    "imgUpright": "images/pentacles_07_u.jpg",
    "imgReversed": "images/pentacles_07_r.jpg",
    "upright": "",
    "reversed": "",
    "uprightLong": "Patience and evaluation define this stage. You’ve planted seeds; results take time. Resist uprooting progress to check its growth. Reflection replaces urgency—review methods, refine effort, trust the unseen stages. Progress is cumulative, not constant. Take satisfaction in consistency rather than outcome.",
    "reversedLong": "Reversed, impatience tempts you to abandon worthwhile work. Boredom disguises discouragement. Instead of quitting, adjust the process: change pace, tools, or expectations. Sometimes rest revives motivation better than overhaul.",
    "promptUpright": "What slow project deserves faith instead of interference?",
    "promptReversed": "What could you tweak—not trash—to regain momentum?"
  },
  {
    "key": "pentacles_08",
    "name": "Eight of Pentacles",
    "imgUpright": "images/pentacles_08_u.jpg",
    "imgReversed": "images/pentacles_08_r.jpg",
    "upright": "",
    "reversed": "",
    "uprightLong": "The craftsman’s card—mastery through repetition. Skill deepens when attention replaces hurry. Pour presence into your work: refine, study, improve. Pride in craftsmanship strengthens identity and income alike. Quality over speed builds legacy.",
    "reversedLong": "Reversed, perfectionism or monotony dull enthusiasm. Overfocus on output steals artistry. Step back to see purpose beyond routine. Re-introduce curiosity—learn a variant, teach, or rest. Joy revives precision.",
    "promptUpright": "Which daily habit quietly shapes your expertise?",
    "promptReversed": "How can you rediscover play inside your practice?"
  },
  {
    "key": "pentacles_09",
    "name": "Nine of Pentacles",
    "imgUpright": "images/pentacles_09_u.jpg",
    "imgReversed": "images/pentacles_09_r.jpg",
    "upright": "",
    "reversed": "",
    "uprightLong": "Independence and earned abundance bloom here. The Nine celebrates self-reliance grounded in gratitude. You’ve built comfort through diligence—pause and enjoy it. Luxury can be simple: unhurried breakfast, tidy workspace, quiet evening. True wealth is autonomy over your time. Appreciate it before chasing more.",
    "reversedLong": "Reversed, accomplishment feels empty or fragile. Maybe you’re hustling past satisfaction. Detach identity from productivity; measure worth by presence. Abundance expands when appreciated, not when defended.",
    "promptUpright": "What small ritual lets you savor the life you’ve built?",
    "promptReversed": "How could you let contentment count as success?"
  },
  {
    "key": "pentacles_10",
    "name": "Ten of Pentacles",
    "imgUpright": "images/pentacles_10_u.jpg",
    "imgReversed": "images/pentacles_10_r.jpg",
    "upright": "",
    "reversed": "",
    "uprightLong": "Legacy, stability, and community wealth. You’re benefiting from long-term effort—yours or your ancestors’. Invest in sustainability: finances, health, and relationships that outlast trends. Share knowledge; mentor or collaborate. Prosperity fulfilled is prosperity distributed.",
    "reversedLong": "Reversed, insecurity or family tension disrupts stability. Clarify shared goals; redefine success collectively. True legacy is value alignment, not material display.",
    "promptUpright": "What tradition or practice would you like to pass forward?",
    "promptReversed": "What core value could unify your circle again?"
  },
  {
    "key": "pentacles_page",
    "name": "Page of Pentacles",
    "imgUpright": "images/pentacles_page_u.jpg",
    "imgReversed": "images/pentacles_page_r.jpg",
    "upright": "",
    "reversed": "",
    "uprightLong": "Eagerness to learn defines this Page. You’re a student of the tangible—budgeting, health, craftsmanship, discipline. Progress comes through small, consistent improvements. Curiosity about “how things work” builds real confidence. Begin where you stand.",
    "reversedLong": "Reversed, distraction or self-doubt delays growth. You might crave results without foundation. Recommit to basics; humility accelerates competence. Progress hidden is still progress.",
    "promptUpright": "What skill would you enjoy mastering slowly?",
    "promptReversed": "What first step could turn intention into practice today?"
  },
  {
    "key": "pentacles_knight",
    "name": "Knight of Pentacles",
    "imgUpright": "images/pentacles_knight_u.jpg",
    "imgReversed": "images/pentacles_knight_r.jpg",
    "upright": "",
    "reversed": "",
    "uprightLong": "Steadfast effort wins the marathon. This Knight moves methodically, building trust through reliability. Discipline now outperforms excitement. Protect routine from boredom by remembering purpose—every small task secures the larger vision.",
    "reversedLong": "Reversed, stagnation or rigidity replaces steady growth. You may feel uninspired or resistant to change. Infuse variation without abandoning commitment: new tools, fresh environment, minor upgrades. Adaptation sustains diligence.",
    "promptUpright": "Which repetitive action quietly guarantees your long-term success?",
    "promptReversed": "What fresh element could renew your consistency?"
  },
  {
    "key": "pentacles_queen",
    "name": "Queen of Pentacles",
    "imgUpright": "images/pentacles_queen_u.jpg",
    "imgReversed": "images/pentacles_queen_r.jpg",
    "upright": "",
    "reversed": "",
    "uprightLong": "The Queen harmonizes practicality and nurture. She builds comfort for herself and others through organization, patience, and warmth. Caregiving becomes empowerment when balanced with self-care. Domestic or financial security blossoms through mindful stewardship.",
    "reversedLong": "Reversed, overextension depletes resources. You may nurture others while neglecting rest or pleasure. Reinvest in your own body and home first; replenishment multiplies generosity.",
    "promptUpright": "What small act of care could make your environment feel more supportive?",
    "promptReversed": "How can you treat your wellbeing as non-negotiable?"
  },
  {
    "key": "pentacles_king",
    "name": "King of Pentacles",
    "imgUpright": "images/pentacles_king_u.jpg",
    "imgReversed": "images/pentacles_king_r.jpg",
    "upright": "",
    "reversed": "",
    "uprightLong": "This King masters stability with generosity. Leadership here means creating systems that sustain others. You’ve proven capability—now focus on legacy: mentorship, ethical growth, long-range planning. Wealth is stewardship, not possession. Ground ambition in gratitude and patience.",
    "reversedLong": "",
    "promptUpright": "How can your success uplift others sustainably?",
    "promptReversed": "What could you release to make success feel peaceful again?"
  }
]
